remote_theme: pmarsceill/just-the-docs
title: TuxJSQL H2
description: Tuxjsql h2 documentation
url: "https://tuxjsql.dev"
baseurl: "/h2/"
aux_links:
  "TuxJSQL Home":
    - "https://tuxjsql.dev"
  "TuxJSQL h2 GitHub":
    - "//github.com/tuxjsql/h2"